name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Demo.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Dist

permissions:
  contents: read

jobs:
  windows:
    strategy:
      matrix:
        platform:
          [
            { arch: "Win32", SDL2libPath: "x86", binPath: "x86" },
            { arch: "x64", SDL2libPath: "x64", binPath: "x86_64" },
          ]
      fail-fast: false
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v3

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build SDL2 statically
        run: |
          git clone https://github.com/libsdl-org/SDL.git
          cd SDL
          git checkout SDL2
          cmake -S . -B build -DSDL_STATIC=ON -DSDL_SHARED=OFF -DSDL_TEST_LIBRARY=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded" -A ${{ matrix.platform.arch }}
          cmake --build build --config Release
          Copy-Item "build\Release\SDL2-static.lib" -destination "..\External\SDL3\lib\${{ matrix.platform.SDL2libPath }}-static-release"

      - name: Prepare MSVC project files
        run: premake5 --file=Build.lua vs2022

      - name: Build
        run: msbuild Demo.sln -nologo -t:rebuild -verbosity:detailed -clp:ForceConsoleColor -m -property:Configuration=Dist -p:Platform=${{ matrix.platform.arch }}

      - name: Upload Demo
        uses: actions/upload-artifact@v4
        with:
          name: Demo (Windows - ${{ matrix.platform.arch }})
          path: Binaries/windows-${{ matrix.platform.binPath }}/Dist

  build-ubuntu64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - name: Install dependencies
        run: sudo apt-get install libsdl2-dev

      # - name: Build SDL2 statically
      #   run: |
      #     git clone https://github.com/libsdl-org/SDL.git
      #     cd SDL
      #     cmake -S . -B build -DSDL_STATIC=ON -DSDL_SHARED=OFF -DSDL_TEST_LIBRARY=OFF
      #     cmake --build build --config Release
      #     cmake --install build

      - name: Generate make file
        run: premake5 --cc=clang --file=Build.lua gmake2

      - name: Build
        run: make config=dist

  #     - name: Upload Rainbow File Explorer
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: Rainbow File Explorer (Linux)
  #         path: Binaries/linux-x86_64/Dist
