name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Demo.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Dist

permissions:
  contents: read

jobs:
  build-win32:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build SDL3 statically
        run: |
          git clone https://github.com/libsdl-org/SDL.git
          cd SDL
          cd VisualC
          msbuild SDL.sln -target:SDL3:Rebuild -verbosity:diag -property:Configuration=Release -property:Platform=Win32 -property:DefineConstants="HAVE_LIBC;SDL_STATIC_LIB" -property:ConfigurationType=StaticLibrary -property:RuntimeLibrary=MT
          copy /Y Win32\Release\*.* ..\..\External\SDL3\lib\x86-static-release

      - name: Prepare MSVC project files
        run: premake5 --file=Build.lua vs2022

      - name: Upload Demo
        uses: actions/upload-artifact@v4
        with:
          name: Demo (Windows - x86)
          path: Binaries/windows-x86/Dist
